version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cadastro_api
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis
    environment:
      - DEBUG=${DEBUG:-0}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-me-in-production}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@10.13.88.6:5432/dev_cadastro_unificado}
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,10.13.65.37}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://10.13.65.37:8001,http://10.13.65.37:8081,http://10.13.65.37:3000}
    
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --reload 

  redis:
    image: redis:7-alpine
    container_name: cadastro_redis
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    container_name: cadastro_nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
  redis_data:

